### PR TITLE
Added OrientDB 2.1.9 to TravisCI configuration.

### PR DESCRIPTION
**Pull request by obi1kenobi**

### CODE REVIEW

**Comment by obi1kenobi** [comment]
I'm not sure why this is failing, I have very little experience with maven. I'd love it if someone else could take a look -- I suspect there is a bug that only happens with OrientDB 2.1.9 and having CI run the tests would be extremely useful.

**Comment by Ostico** [comment]
Hi @obi1kenobi ,

i suppose there is an error in the CI script for Maven build, maybe the repo URL is not the right one. I must test this more in detail.

**Comment by obi1kenobi** [comment]
Not a problem :) Also, it may be a good idea to add the new OrientDB versions up to 2.1.15

**Comment by Ostico** [comment]
There is a Bug in the OrientDB >= 2.1.9 when the DEBUG on the Binary protocol is activated, so i must change the configuration script for these versions and the CI script.

This is for Maven 
https://github.com/orientechnologies/orientdb/issues/5879

and this is for the DEBUG flag:
https://github.com/orientechnologies/orientdb/issues/5962

**Pull request closed without merging**
