### PR TITLE
Allow sanitising of batch variable names.

### PR DESCRIPTION
**Pull request by obi1kenobi**
I only fixed the merge conflict between `develop` and #139. I'm not convinced that the name cleaning approach in batch.py is the right way to go though -- it allows sanitization to be turned off, silently replaces invalid chars rather than throwing exceptions, and might itself be vulnerable to SQL injection. It's certainly better than not having any sanitization whatsoever (the current state), but I think it needs more work before I'd consider it production-ready.

### CODE REVIEW

**Comment by obi1kenobi** [comment]
Not sure why the CI build failed, the test file didn't get changed and looks fine to me. I restarted the build, and we'll see what happens now.

**Comment by obi1kenobi** [comment]
@mogui this is really weird, and I can't figure out what's going on. The test claims that on the line:
```
class OGMAnimalsTestCase(OGMAnimalsTestCaseBase):
```
we have that `OGMAnimalsTestCaseBase` is undefined, even though its definition is ~10 lines above that. Furthermore, the test claims that the problematic line is line 65 in its file, whereas my editor shows it as line 52. The file in question wasn't modified in this commit.

Thoughts on what's going on? Can you pull the branch manually and test it locally? The tests run fine on my machine.

**Comment by mogui** [comment]
wait @obi1kenobi it was my fault messing with the merge I've now restored it correctly :)
Something is wrong with Travis it seems that randomly it doesn't launch orient correctly and tests fails failing the connection :O

**Comment by obi1kenobi** [comment]
Restarting the build again, hopefully it'll work this time :)

**Comment by obi1kenobi** [comment]
Great. The last thing would be to update PyPI with a new version that has all these extra checks, if you have a moment.

**Pull request merged**
