### PR TITLE
Object-Graph Mapper Interfaces. Script Management. Correct handling of Decimals.

### PR DESCRIPTION
**Pull request by TropicalPenguin**
Hello,

I started making these changes mostly because the Bulbs project had no obvious way to properly specify and communicate Decimal properties on classes. If you have used sqlalchemy before, you will notice its strong influence on the 'ogm' layer here.

I trust these additions will be valuable, since I see there have been multiple false-starts along similar lines. And according to http://www.slideshare.net/fphhotchips/a-quick-review-of-python-and-graph-databases, they seem one of the main things holding OrientDB back for python developers.

### CODE REVIEW

**Comment by TropicalPenguin** [comment]
I should mention, these changes are also dependent on the recent changes to expose Gremlin functionality by @lebedov

**Comment by TropicalPenguin** [comment]
These most recent changes make the query interfaces substantially more expressive. Still to come, support for the TRAVERSE command.

**Comment by davidkyalo** [comment]
Hi
@TropicalPenguin Great features you have added there. And as you've mentioned, lack  of ogm features is one of the things holding orientdb back. 

I had actually started a similar library (https://github.com/davidkyalo/orientedpy) a while back though I haven't had time to do much. The idea behind Orientedpy was to create a simple OGM driven by pyorient.

However I think having these features under pyorient would be better. And that way we can focus our efforts in maintaining it.

**Comment by Ostico** [comment]
Hi all,

@TropicalPenguin  i'm very happy you worked on that, i will merge your code and add this Pyorient.
In my mind the driver would have had to grow up so, with the contribution of all users, so i can use the time to work at the internals. 

I will mention this feature in the Readme and i will quote it as early development stage and to be tested. More documentation, tests or code for that is welcome.

@davidkyalo thank you, if you want contribute directly to this driver you're welcome too.

Thank you again

**Pull request merged**
