### PR TITLE
Faster parsing with regex (~10x for numbers & RIDs)

### PR DESCRIPTION
**Pull request by thenesk**
The modifications improve performance of _parse_rid(), _parse_value(), _parse_number(), and _parse_string(), all in the OrientSerializationCSV class.  Added test_performance.py with timing and optional profiling.

### CODE REVIEW

**Comment by thenesk** [comment]
I tested pretty heavily, including with different versions of python.  It looks like the failures in CI are unrelated to this PR.  I also tried these changes in my copy of the master branch and they seem to test clean there.  I'd love to get this change in to improve performance.  Of course in the longer term, the binary protocol approach looks very promising.

**Comment by thenesk** [comment]
If you do like this performance improvement, there is another (more modest) improvement I am tinkering with.

**Comment by thenesk** [comment]
Any thoughts on this PR?

**Comment by thenesk** [comment]
This should also help with #209 as negative RID values are parsed

**Comment by Ostico** [comment]
Thank you @thenesk ,
in the next release this will be available.

**Pull request merged**
