### PR TITLE
Allow sanitising of/exceptions on invalid batch variable names.

### PR DESCRIPTION
**Pull request by TropicalPenguin**
Provides solutions to #137 .

### CODE REVIEW

**Comment by TropicalPenguin** [comment]
This latest commit is in response to #140

**Comment by mogui** [comment]
@TropicalPenguin @obi1kenobi Can you help us out?
 I don't know how to fix the little issue that there is in the merge without the possibility to break things

**Comment by obi1kenobi** [comment]
I'll take a look!

**Comment by obi1kenobi** [comment]
#173 is merged, and contained the last of the unmerged changes from this PR. Therefore, this can now be closed.

**Pull request closed without merging**
